### ISSUE TITLE
Integrate UnitFramesImproved

### ISSUE THREAD

**Issue by ghost** [obble/modui#34]
I would love to see an option to toggle the unit frames between the default ones and the improved ones. The UnitFramesImproved addon works just fine with modui but the texture for the hp/mana bars remains the one from modui and doesn't look all that good. An integration with the default modui would be amazing.

Here's the link to the addon: https://github.com/Ko0z/UnitFramesImproved_Vanilla

**Comment by kev41** [comment]
If you implement this addon, I hope its toggable becacuse I love the current one.

**Comment by Steffen-Hadberg-Nielsen** [comment]
Ko0z just added ModUI compatiblility to UnitFramesImproved, it does a bit more than just making the healthbar large though such as using his class colors and makes NPC's have Warrior class colored frames if they are melee and Mage color if they're ranged etc... minor things

**Comment by obble** [comment]
with UnitFramesImproved offering support im closing this, as I only intended to introduce compatibility between the two addons rather than adding additional functionality.

there's also the addon [modui_ified](https://github.com/trulynullified/modui_ified) that apparently adds this form of unitframe style

**Comment by Ko0z** [comment]
Yes, there's now automatic detection and compatibility between modUI and UnitFramesImproved_Vanilla. I'm going to fix the colors of the healthbars/manabars later today. ( They are a bit tinted atm for some reason)
