### ISSUE TITLE
Nameplates not scaling with UI

### ISSUE THREAD

**Issue by Bynzski** [obble/modui#72]
I scale my UI down quite a bit but the nameplates seem to be hard coded to a specific size. This makes the nameplates look extremely large.

Maybe not scaling to UI, but an option for scaling nameplates would be great!

**Comment by obble** [comment]
on some testing i think this might be an issue with the vanilla client rather than modui?

**Comment by obble** [comment]
can confirm that this is built into the game rather than caused by modui.

nameplates are really hard to resize without causing them to offset or be placed weirdly, so for now i will be keeping them at a fixed size. you could potentially  try and manually adjust the values [here](https://github.com/obble/modui/blob/master/nameplate/nameplates.lua#L184) though, changing x in  :SetWidth(x) to something smaller.

Thanks.
